/**
 * ZPL Label Generator for Zebra thermal printers.
 *
 * Generates ZPL II commands for 4×6 package labels containing:
 * - Customer name and PMB number
 * - Tracking number with Code 128 barcode
 * - Carrier and date
 * - Store info
 *
 * Print via raw TCP to printer IP:9100 or window.print() fallback.
 */

export interface ZplLabelData {
  customerName: string;
  pmbNumber: string;
  trackingNumber: string;
  carrier: string;
  date: string;
  storeName?: string;
  storeAddress?: string;
  packageType?: string;
  senderName?: string;
}

/**
 * Generate ZPL II code for a 4×6 package label.
 *
 * Uses 203 DPI coordinates (standard for Zebra GK/GC/ZD series).
 * Label dimensions: 4" wide × 6" tall = 812 × 1218 dots at 203 DPI.
 */
export function generateZplLabel(data: ZplLabelData): string {
  const {
    customerName,
    pmbNumber,
    trackingNumber,
    carrier,
    date,
    storeName = 'ShipOS Pro',
    storeAddress = '',
    packageType = 'Package',
    senderName = '',
  } = data;

  // Truncate long strings to fit label width
  const truncate = (str: string, max: number) =>
    str.length > max ? str.slice(0, max - 1) + '…' : str;

  const carrierUpper = carrier.toUpperCase();
  const trackingDisplay = truncate(trackingNumber, 30);
  const nameDisplay = truncate(customerName, 28);

  return [
    // ── Start label ──────────────────────────────────────────────────────
    '^XA',                          // Start format
    '^CF0,30',                      // Default font: 30pt

    // ── Header: Store name ───────────────────────────────────────────────
    '^FO30,30^A0N,36,36',          // Position & font size
    `^FD${truncate(storeName, 30)}^FS`,

    // Store address (smaller)
    ...(storeAddress ? [
      '^FO30,70^A0N,22,22',
      `^FD${truncate(storeAddress, 40)}^FS`,
    ] : []),

    // ── Divider line ─────────────────────────────────────────────────────
    '^FO20,100^GB770,2,2^FS',

    // ── Carrier badge ────────────────────────────────────────────────────
    '^FO30,120^A0N,48,48',
    `^FD${carrierUpper}^FS`,

    // ── Package type (right aligned) ─────────────────────────────────────
    `^FO550,120^A0N,28,28`,
    `^FD${packageType}^FS`,

    // ── Date ─────────────────────────────────────────────────────────────
    `^FO550,150^A0N,22,22`,
    `^FD${date}^FS`,

    // ── Divider line ─────────────────────────────────────────────────────
    '^FO20,190^GB770,2,2^FS',

    // ── DELIVER TO section ───────────────────────────────────────────────
    '^FO30,210^A0N,22,22',
    '^FDDELIVER TO:^FS',

    // Customer name (large)
    '^FO30,245^A0N,42,42',
    `^FD${nameDisplay}^FS`,

    // PMB number (prominent)
    '^FO30,295^A0N,36,36',
    `^FD${pmbNumber}^FS`,

    // ── Sender info ──────────────────────────────────────────────────────
    ...(senderName ? [
      '^FO30,350^A0N,22,22',
      '^FDFROM:^FS',
      '^FO30,375^A0N,28,28',
      `^FD${truncate(senderName, 35)}^FS`,
    ] : []),

    // ── Divider line ─────────────────────────────────────────────────────
    '^FO20,420^GB770,2,2^FS',

    // ── Tracking section ─────────────────────────────────────────────────
    '^FO30,440^A0N,22,22',
    '^FDTRACKING NUMBER:^FS',

    // Tracking number text
    '^FO30,470^A0N,28,28',
    `^FD${trackingDisplay}^FS`,

    // ── Code 128 barcode ─────────────────────────────────────────────────
    '^FO30,520^BY2',               // Bar code defaults: 2 dot wide
    '^BCN,120,Y,N,N',             // Code 128: 120 dots high, print interpretation
    `^FD${trackingNumber}^FS`,

    // ── Footer ───────────────────────────────────────────────────────────
    '^FO20,680^GB770,2,2^FS',

    '^FO30,695^A0N,20,20',
    '^FDGenerated by ShipOS Pro^FS',

    // ── End label ────────────────────────────────────────────────────────
    '^XZ',                          // End format
  ].join('\n');
}

/**
 * Send ZPL data to a network printer via raw TCP (from browser).
 *
 * Attempts to POST raw ZPL text to the printer's IP on port 9100.
 * Falls back to window.print() if the network request fails.
 */
export async function printZplLabel(
  zpl: string,
  printerIp?: string,
  printerPort: number = 9100
): Promise<{ success: boolean; method: 'network' | 'browser'; error?: string }> {
  // Try network print if IP is provided
  if (printerIp) {
    try {
      const response = await fetch(`http://${printerIp}:${printerPort}`, {
        method: 'POST',
        body: zpl,
        headers: { 'Content-Type': 'application/x-zpl' },
        signal: AbortSignal.timeout(5000),
      });

      if (response.ok || response.status === 0) {
        return { success: true, method: 'network' };
      }
    } catch {
      // Network print failed — fall through to browser print
    }
  }

  // Fallback: open a print dialog with a formatted version
  try {
    const printWindow = window.open('', '_blank', 'width=400,height=600');
    if (printWindow) {
      printWindow.document.write(`
        <html>
        <head><title>Print Label</title>
        <style>
          @page { size: 4in 6in; margin: 0; }
          body { font-family: monospace; white-space: pre-wrap; font-size: 10px; padding: 8px; }
        </style>
        </head>
        <body>${zpl.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</body>
        </html>
      `);
      printWindow.document.close();
      printWindow.print();
      return { success: true, method: 'browser' };
    }
    return { success: false, method: 'browser', error: 'Could not open print window' };
  } catch (err) {
    return {
      success: false,
      method: 'browser',
      error: err instanceof Error ? err.message : 'Print failed',
    };
  }
}
